@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvZHJpZ29Ac2l4cHJvLnBybyIsImlhdCI6MTY0Nzk5NDMzNSwiZXhwIjoxNjQ3OTk3OTM1LCJzdWIiOiIxIn0.clkDJave-4NMnwjgGDWp-fWtzzFXrAkTHVv92v2B20E
### LOGIN
POST https://fake-api-json-server-recrutati.herokuapp.com/login
content-type: application/json

{
  "email": "rodrigo@sixpro.pro",
  "password": "Teste123!"
}


### GASTOS
GET https://fake-api-json-server-recrutati.herokuapp.com/660/gastos
Authorization: Bearer {{TOKEN}}

### CREATE
POST https://fake-api-json-server-recrutati.herokuapp.com/660/gastos
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
  "tipo": 0,
  "data": "15/01/2022",
  "preco": 7.77,
  "valor": 150.00,
  "odometro": 35000
}

### UPDATE
PUT https://fake-api-json-server-recrutati.herokuapp.com/660/gastos/5
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
  "tipo": 1,
  "data": "10/01/2022",
  "preco": 7.5,
  "valor": 130.00,
  "odometro": 34000
}


### GET GASTO
GET https://fake-api-json-server-recrutati.herokuapp.com/660/gastos/5
Authorization: Bearer {{TOKEN}}

### DELETE GASTO
DELETE https://fake-api-json-server-recrutati.herokuapp.com/660/gastos/5
Authorization: Bearer {{TOKEN}}
